version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - ./mongodb_data:/data/db
  # warface:
  #   build: './'
  #   container_name: warface
  #   ports:
  #     - "${PORT}:${PORT}"
    
    

volumes:
  mongodb_data:
